export const ACTION_FETCHING_DATA = "ACTION_FETCHING_DATA";
export const ACTION_FETCHED_DATA = "ACTION_FETCHED_DATA";
export const ACTION_FETCH_FAIL_DATA = "ACTION_FETCH_FAIL_DATA";
export const ACTION_FETCH_REQUEST = "ACTION_FETCH_REQUEST";